name: PROD Build and Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build-and-publish:
    runs-on: [self-hosted]
    env:
      NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
      REPOSITORY: registry.dawninternet.net/dawn-foundation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Dawn Internet Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.dawninternet.net
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push to Dawn Internet Container Registry
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{env.REPOSITORY}}/prod_infrafi_web:${{ github.ref_name }}
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
            NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
            NEXT_PUBLIC_API_URL=${{ secrets.PROD_API_URL }}
            NEXT_PUBLIC_M0_QUOTE_PREVIEW_WALLET=${{ secrets.NEXT_PUBLIC_M0_QUOTE_PREVIEW_WALLET }}
            NEXT_PUBLIC_GLOW_QUOTE_SIMULATION_OWNER=${{ secrets['NEXT_PUBLIC_GLOW_QUOTE_SIMULATION_OWNER'] }}
            NEXT_PUBLIC_GLOW_VAULT_ADDRESS=${{ secrets.MAINNET_GLOW_VAULT_ADDRESS }}

  prod-deploy:
    runs-on: [self-hosted]
    needs: build-and-publish
    steps:
      - name: Generate cd-dawn token (GitHub App)
        uses: actions/create-github-app-token@v2
        id: gitops
        with:
          app-id: ${{ secrets.CD_DAWN_APP_ID }}
          private-key: ${{ secrets.CD_DAWN_APP_KEY }}
          owner: DAWN-Foundation
          repositories: cd-dawn

      - name: Clone gitops repository (cd-dawn)
        run: git clone https://x-access-token:${{ steps.gitops.outputs.token }}@github.com/DAWN-Foundation/cd-dawn.git

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o ./yq
          chmod +x ./yq
        working-directory: cd-dawn

      - name: Update image tag
        run: ./yq e '.image.tag = "${{ github.ref_name }}"' -i apps/services/infrafi-web-prod/values.yaml
        working-directory: cd-dawn

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/services/infrafi-web-prod/values.yaml
          git commit -m "infrafi-web prod -> ${{ github.ref_name }}" || { echo "no changes"; exit 0; }
          git push origin HEAD:main
        working-directory: cd-dawn
